# Generated by Django 5.2.4 on 2025-07-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_answer_question_test_attempt_givenanswer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='owner',
        ),
        migrations.AddConstraint(
            model_name='givenanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_given_answer_pet_attempt_and_question'),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
