# Generated by Django 5.2.4 on 2025-07-10 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_note_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('language', models.CharField(default='python', max_length=30)),
                ('time_limit', models.FloatField(default=2.0)),
                ('memory_limit', models.IntegerField(default=128)),
                ('docker_image', models.CharField(default='python:3.12-alpine', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('stderr', models.TextField(blank=True)),
                ('stdout', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdin', models.TextField()),
                ('expected_out', models.TextField()),
                ('weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='givenanswer',
            name='unique_given_answer_pet_attempt_and_question',
        ),
        migrations.AddConstraint(
            model_name='givenanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='one_question_one_answer'),
        ),
        migrations.AddField(
            model_name='programmingquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_tasks', to='base.test'),
        ),
        migrations.AddField(
            model_name='submission',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='base.attempt'),
        ),
        migrations.AddField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.programmingquestion'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='base.programmingquestion'),
        ),
    ]
