# Generated by Django 5.2.4 on 2025-07-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_programmingquestion_submission_testcase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
