# Generated by Django 5.2.4 on 2025-07-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_attempt_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='max_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
